from enum import Enum


class CategoryCode(str, Enum):
    HOUSING = "HOUSING"
    LOAN = "LOAN"
    WEDDING = "WEDDING"
    TAX = "TAX"
    CHILDCARE = "CHILDCARE"


class EvaluationStatus(str, Enum):
    LIKELY_ELIGIBLE = "LIKELY_ELIGIBLE"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    AVAILABLE_LATER = "AVAILABLE_LATER"
    LIKELY_INELIGIBLE = "LIKELY_INELIGIBLE"
    OFFICIAL_CONFIRMATION_REQUIRED = "OFFICIAL_CONFIRMATION_REQUIRED"


class PolicyRelationType(str, Enum):
    BEFORE = "BEFORE"
    AFTER = "AFTER"
    RELATED = "RELATED"
    ALTERNATIVE = "ALTERNATIVE"
    CONFLICT = "CONFLICT"
    REEVALUATE_AFTER = "REEVALUATE_AFTER"


class DocumentType(str, Enum):
    OVERVIEW = "OVERVIEW"
    ELIGIBILITY = "ELIGIBILITY"
    APPLICATION = "APPLICATION"
    DOCUMENTS = "DOCUMENTS"
    FAQ = "FAQ"
    CAUTION = "CAUTION"
